export const ADDINGREDIENT = 'ADDINGREDIENT';
export const DELETEINGREDIENT = 'DELETEINGREDIENT';
export const REMOVESELECTEDINGREDIENT = 'REMOVESELECTEDINGREDIENT';
export const SETFOODTYPE = "SETFOODTYPE";
export const SELECTINGREDIENT = 'SELECTINGREDIENT';